/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ActionName = "DELETE" | "INSERT" | "UPDATE";

export type AuthProvider = "apple" | "facebook" | "github" | "google";

export type BookingStatus = "cancelled" | "completed" | "confirmed" | "in_progress" | "pending" | "rejected";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LocationType = "client_home" | "other" | "park" | "sitter_home";

export type Numeric = ColumnType<string, number | string, number | string>;

export type ServiceType = "boarding" | "daycare" | "dog_walking" | "grooming" | "overnight_stay" | "pet_taxi" | "training" | "vet_visits";

export type Sex = "female" | "male";

export type SizeCategory = "giant" | "large" | "medium" | "small" | "tiny";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type VaccinationStatus = "fully_vaccinated" | "not_vaccinated" | "partially_vaccinated" | "unknown";

export type VerificationStatus = "approved" | "pending" | "rejected";

export interface Availability {
  created_at: Generated<Timestamp>;
  day_of_week: number;
  end_time: string;
  id: Generated<number>;
  sitter_id: number;
  start_time: string;
  updated_at: Generated<Timestamp>;
}

export interface Bookings {
  client_id: number;
  created_at: Generated<Timestamp>;
  dog_id: number;
  end_date: Timestamp;
  id: Generated<number>;
  location_address: string | null;
  location_type: LocationType;
  service_id: number | null;
  sitter_id: number;
  special_instructions: string | null;
  start_date: Timestamp;
  status: Generated<BookingStatus>;
  total_price: Numeric | null;
  updated_at: Generated<Timestamp>;
}

export interface DogBreeds {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  requires_certificate: Generated<boolean>;
  size_category: SizeCategory;
}

export interface Dogs {
  age_months: number | null;
  age_years: number | null;
  breed_id: number | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_neutered: boolean | null;
  medical_conditions: string | null;
  mixed_breed: Generated<boolean>;
  name: string;
  owner_id: number;
  photo_url: string | null;
  sex: Sex;
  special_care_requirements: string | null;
  temperament: string | null;
  updated_at: Generated<Timestamp>;
  vaccination_status: Generated<VaccinationStatus>;
  weight_kg: Numeric | null;
}

export interface GeographyColumns {
  coord_dimension: number | null;
  f_geography_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface GeometryColumns {
  coord_dimension: number | null;
  f_geometry_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface OauthAccounts {
  access_token: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: Generated<number>;
  provider: AuthProvider;
  provider_user_id: string;
  refresh_token: string | null;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface Reviews {
  booking_id: number | null;
  comment: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  rating: number;
  reviewee_id: number;
  reviewer_id: number;
  updated_at: Generated<Timestamp>;
}

export interface Revisions {
  action: ActionName;
  changed_fields: string[] | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  new_values: Json | null;
  old_values: Json | null;
  record_id: string;
  table_name: string;
  user_id: number | null;
}

export interface SitterBreedSpecialties {
  additional_notes: string | null;
  breed_id: number;
  created_at: Generated<Timestamp>;
  experience_years: Generated<number>;
  sitter_id: number;
}

export interface SitterCertificates {
  admin_notes: string | null;
  certificate_file_path: string | null;
  certificate_name: string;
  created_at: Generated<Timestamp>;
  expiration_date: Timestamp | null;
  id: Generated<number>;
  issue_date: Timestamp | null;
  issuing_organization: string;
  sitter_id: number;
  updated_at: Generated<Timestamp>;
  verification_status: Generated<VerificationStatus>;
}

export interface Sitters {
  bio: string | null;
  can_host_at_home: Generated<boolean>;
  created_at: Generated<Timestamp>;
  daily_rate: Numeric | null;
  hourly_rate: Numeric | null;
  id: Generated<number>;
  is_available: Generated<boolean>;
  last_location_update: Timestamp | null;
  max_dogs_at_once: Generated<number>;
  service_radius_km: Numeric | null;
  updated_at: Generated<Timestamp>;
  user_id: number;
  verification_status: Generated<VerificationStatus>;
  years_experience: number | null;
}

export interface SitterServices {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  is_available: Generated<boolean>;
  price: Numeric | null;
  service_name: ServiceType;
  sitter_id: number;
  updated_at: Generated<Timestamp>;
}

export interface SpatialRefSys {
  auth_name: string | null;
  auth_srid: number | null;
  proj4text: string | null;
  srid: number;
  srtext: string | null;
}

export interface UnavailableDates {
  created_at: Generated<Timestamp>;
  end_date: Timestamp;
  id: Generated<number>;
  reason: string | null;
  sitter_id: number;
  start_date: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface UserGroupMemberships {
  created_at: Generated<Timestamp>;
  group_id: number;
  user_id: number;
}

export interface UserGroups {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  name: string;
  permissions: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  address: string | null;
  avatar_url: string | null;
  bio: string | null;
  city: string | null;
  country: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  is_active: Generated<boolean>;
  is_email_verified: Generated<boolean>;
  latitude: Numeric | null;
  location: string | null;
  longitude: Numeric | null;
  name: string;
  permissions: Generated<Json>;
  phone: string | null;
  postal_code: string | null;
  state: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  availability: Availability;
  bookings: Bookings;
  dog_breeds: DogBreeds;
  dogs: Dogs;
  geography_columns: GeographyColumns;
  geometry_columns: GeometryColumns;
  oauth_accounts: OauthAccounts;
  reviews: Reviews;
  revisions: Revisions;
  sitter_breed_specialties: SitterBreedSpecialties;
  sitter_certificates: SitterCertificates;
  sitter_services: SitterServices;
  sitters: Sitters;
  spatial_ref_sys: SpatialRefSys;
  unavailable_dates: UnavailableDates;
  user_group_memberships: UserGroupMemberships;
  user_groups: UserGroups;
  users: Users;
}
