/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Posts {
  content: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  title: string | null;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  posts: Posts;
  users: Users;
}
