services:
    postgres:
        image: postgres:17
        container_name: postgres
        restart: unless-stopped
        networks:
            - hunde_sitting
        ports:
            - 5432:5432
            # set shared memory limit when using docker-compose
        shm_size: 128mb
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PORT=${POSTGRES_PORT}

networks:
    hunde_sitting:
        name: hunde_sitting